group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
unstable_features = true
