[package]
name = "aidanpinard-co"
version = "0.1.0"
edition = "2021"
description = "Yew App for aidanpinard.co"
readme = "README.md"
repository = "https://github.com/jeiang/website"
license = "MIT OR Apache-2.0"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]

[dependencies]
log = { version = "0.4.17", features = [ "kv_unstable_serde" ] }
serde = {version = "1.0.152", features = [ "derive" ] }
wasm-logger = "0.2.0"
yew = { version = "0.20", features = [ "csr" ] }
yew-router = "0.17.0"
